const EMAIL_IS_EMPTY = "EMAIL_IS_EMPTY";
const PASSWORD_IS_EMPTY = "PASSWORD_IS_EMPTY";
const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  "PASSWORD_LENGTH_MUST_BE_MORE_THAN_8";
const WRONG_PASSWORD = "WRONG_PASSWORD";
const SOME_THING_WENT_WRONG = "SOME_THING_WENT_WRONG";
const USER_EXISTS_ALREADY = "USER_EXISTS_ALREADY";
const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";
const TOKEN_IS_EMPTY = "TOKEN_IS_EMPTY";
const EMAIL_IS_IN_WRONG_FORMAT = "EMAIL_IS_IN_WRONG_FORMAT";

module.exports = {
  EMAIL_IS_EMPTY,
  PASSWORD_IS_EMPTY,
  PASSWORD_LENGTH_MUST_BE_MORE_THAN_8,
  WRONG_PASSWORD,
  SOME_THING_WENT_WRONG,
  USER_EXISTS_ALREADY,
  USER_DOES_NOT_EXIST,
  TOKEN_IS_EMPTY,
  EMAIL_IS_IN_WRONG_FORMAT,
};
